server :
  port : 8081
  include-message : always
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/db_crud_jwt
    username: admin
    password: zayndev
    driver-class-name: com.mysql.cj.jdbc.Driver