server :
  port : 8081
  include-message : always
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/db_crud_jwt
    username: admin
    password: zayndev
    driver-class-name: com.mysql.cj.jdbc.Driver
security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 3600000  # 1h in milliseconds